services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: app_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network  

  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MongoDB__ConnectionString=mongodb://<USER>:<PASSWORD>@mongodb:27017/?authSource=admin
      - ServiceBus__ConnectionString=
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge